=== dfan97/Communesoft.Editor.Stellaris/Communesoft.Editor.Stellaris/Metadata/Xsd/common.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema targetNamespace="https://github.com/dfan97" xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:this="https://github.com/dfan97" xmlns:custom="https://github.com/dfan97/custom" xmlns:types="https://github.com/dfan97/types" xmlns:dirs="https://github.com/dfan97/dirs">

	<import namespace="https://github.com/dfan97/types" schemaLocation="types.xsd" />
	<import namespace="https://github.com/dfan97/dirs" schemaLocation="directories.xsd" />
	
	<include schemaLocation="common-complex.xsd" />
	<include schemaLocation="common-list.xsd" />
	<include schemaLocation="common-ref.xsd" />
	<include schemaLocation="common-simple.xsd" />

	<simpleType name="stringNoWS">
		<annotation>
			<documentation xml:lang="en">
				A whitespaceless string.
			</documentation>
		</annotation>
		<restriction base="string">
			<pattern value="\S*" />
		</restriction>
	</simpleType>
	<simpleType name="stringNotNull">
		<annotation>
			<documentation xml:lang="en">
				Not empty string.
			</documentation>
		</annotation>
		<restriction base="this:stringNoWS">
			<minLength value="1" />
		</restriction>
	</simpleType>

	<complexType name="annotatable" abstract="true">
		<sequence>
			<element name="annotation" minOccurs="0">
				<simpleType>
					<annotation>
						<documentation xml:lang="en">
							An annotation, displaying in interface.
						</documentation>
					</annotation>
					<restriction base="string" />
				</simpleType>
			</element>
		</sequence>
	</complexType>

	<complexType name="appearance" abstract="true">
		<complexContent>
			<extension base="this:annotatable">
				<attribute name="scope" default="all">
					<annotation>
						<documentation xml:lang="en">
							Scope types, where the expression can appears.
						</documentation>
					</annotation>
					<simpleType>
						<restriction>
							<simpleType>
								<list itemType="types:scope.type" />
							</simpleType>
							<minLength value="1" />
						</restriction>
					</simpleType>
				</attribute>
				<attribute name="default" type="string">
					<annotation>
						<documentation xml:lang="en">
							A default value for the expression.
						</documentation>
					</annotation>
				</attribute>
				<attribute name="min" type="nonNegativeInteger">
					<annotation>
						<documentation xml:lang="en">
							Minimum count of appearing.
						</documentation>
					</annotation>
				</attribute>
				<attribute name="max">
					<annotation>
						<documentation xml:lang="en">
							Maximum count of appearing. '*' is unbounded count.
						</documentation>
					</annotation>
					<simpleType>
						<union memberTypes="positiveInteger">
							<simpleType>
								<restriction base="string">
									<enumeration value="*">
										<annotation>
											<documentation xml:lang="en">
												Unbounded count of appearing.
											</documentation>
										</annotation>
									</enumeration>
								</restriction>
							</simpleType>
						</union>
					</simpleType>
				</attribute>

				<assert test="not(exists(@min) and exists(@max) and (number(@min) gt number(@max)))">
					<annotation>
						<documentation xml:lang="en">
							Maximum less than minimum.
						</documentation>
					</annotation>
				</assert>
			</extension>
		</complexContent>
	</complexType>

	<attributeGroup name="value.interval.attrs">
		<attribute name="min-value" type="decimal">
			<annotation>
				<documentation xml:lang="en">
					Minimum for numeric value.
				</documentation>
			</annotation>
		</attribute>
		<attribute name="max-value" type="decimal">
			<annotation>
				<documentation xml:lang="en">
					Maximum for numeric value.
				</documentation>
			</annotation>
		</attribute>
	</attributeGroup>


	<complexType name="enum">
		<complexContent>
			<extension base="this:appearance">
				<choice minOccurs="0">
					<element name="extension" type="this:enum.values">
						<annotation>
							<documentation xml:lang="en">
								Extends expression with new key values.
							</documentation>
						</annotation>
					</element>
					<element name="restriction" type="this:enum.values">
						<annotation>
							<documentation xml:lang="en">
								Restricts expression with key values.
							</documentation>
						</annotation>
					</element>
				</choice>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="enum.values">
		<annotation>
			<documentation xml:lang="en">
				Enumeration values.
			</documentation>
		</annotation>
		<sequence>
			<element name="enum" type="this:enum.value" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	<complexType name="enum.value">
		<complexContent>
			<extension base="this:annotatable">
				<attribute name="value" type="this:stringNotNull" use="required">
					<annotation>
						<documentation xml:lang="en">
							An enumeration value.
						</documentation>
					</annotation>
				</attribute>
			</extension>
		</complexContent>
	</complexType>




	<complexType name="file">
		<complexContent>
			<extension base="this:annotatable">
				<attribute name="path" type="dirs:path" use="required" />
			</extension>
		</complexContent>
	</complexType>
	<element name="file">
		<annotation>
			<documentation xml:lang="en">
				Representing file structure.
			</documentation>
		</annotation>

		<alternative test="exists(@type)">
			<complexType>
				<annotation>
					<documentation xml:lang="en">
						Shorthand for one-type file with type related or strictly named reference.
					</documentation>
				</annotation>

				<complexContent>
					<extension base="this:file">
						<attribute name="type" type="types:common" use="required">
							<annotation>
								<documentation xml:lang="en">
									Contained type.
								</documentation>
							</annotation>
						</attribute>
						<attribute name="entity" type="types:entity" default="{string}" />

						<!--<assert test="not(exists(@min) and exists(@max) and (number(@min) gt number(@max)))">
							<annotation>
								<documentation xml:lang="en">
									Maximum less than minimum.
								</documentation>
							</annotation>
						</assert>-->
					</extension>
				</complexContent>
			</complexType>
		</alternative>

		<alternative test="true()">
			<complexType>
				<annotation>
					<documentation xml:lang="en">
						Standard description form.
					</documentation>
				</annotation>

				<complexContent>
					<extension base="this:file">
						<group ref="this:scope" />
					</extension>
				</complexContent>
			</complexType>
		</alternative>
	</element>


	<element name="files">
		<annotation>
			<documentation xml:lang="en">
				Contains files structures.
			</documentation>
		</annotation>

		<complexType>
			<sequence>
				<element ref="this:file" maxOccurs="unbounded" />
			</sequence>
		</complexType>
		<unique name="UX_files_path">
			<selector xpath="this:file" />
			<field xpath="@path" />
		</unique>
	</element>
</schema>

=== dfan97/Communesoft.Editor.Stellaris/Metadata/Xml/_files.xml
<?xml version="1.0" encoding="utf-8"?>
<files xmlns="https://github.com/dfan97" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/dfan97 ../Xsd/common.xsd">
	<file path="common/agendas" type="{government-agenda}" />
	<file path="common/ai_budget" type="{economic-budget}" />
	<file path="common/ambient_objects" type="{ambient}" entity="ambient_object" />
	<file path="common/anomalies" type="{anomaly}" />

	<file path="common/archaeological_site_types" type="{archeology}" />
	<file path="common/armies" type="{army}" />
	<file path="common/artifact_actions" type="{relic-act}" />

	<file path="common/ascension_perks" type="{ascension}" />
	<file path="common/asteroid_belts" type="{asteroids}" />


	<file path="common/bombardment_stances" type="{fleet-stance}" />
	<file path="common/buildings" type="{building}" />
	<file path="common/bypass" type="{bypass}" />


	<file path="common/component_sets" type="{ship-design-component-set}" entity="component_set" />
	<file path="common/component_slot_templates" type="{ship-design-component-slot}" />
	<file path="common/component_tags" type="{ship-design-component-tag}" />
	<file path="common/component_templates" type="{ship-design-component}" />


	<file path="common/defines" type="{game-consts}" />
	<file path="common/districts" type="{district}" />


	<file path="common/economic_categories" type="{economic}" />
	<file path="common/edicts" type="{edict}" />
	<file path="common/ethics">
		<complex entity="qwe" type="{fleet-order}">
		</complex>
		<complex entity="qwe2" type="{resolution-trigger}">
		</complex>
		<complex entity="ethic_categories">
			<complex entity="{string}" type="{ethic-category}" min="1" />
		</complex>
		<complex entity="{string}" type="{ethic}" />
	</file>


	<file path="common/global_ship_designs" type="{ship-design}" entity="ship_design" />
	<file path="common/governments" type="{government}" />
	<file path="common/governments/authorities" type="{government-authority}" />
	<file path="common/governments/civics" type="{government-civic}" />


	<file path="common/leader_classes" type="{leader}" entity="{leader-category}" />


	<file path="common/mandates" type="{government-mandate}" />
	<file path="common/megastructures" type="{megastructure}" />


	<file path="common/planet_classes">
		<complex entity="{string}" type="{planet}" />
		<complex entity="random_list" type="{planet-namelist}" />
	</file>
	<file path="common/policies" type="{policy}" />


	<file path="common/relics" type="{relic}" />


	<file path="common/section_templates" type="{ship-design-section}" entity="ship_section_template" />
	<file path="common/ship_behaviors" type="{ship-behavior}" entity="ship_behavior" />
	<file path="common/ship_sizes" type="{ship-size}" />
	<file path="common/solar_system_initializers" type="{system}" />
	<file path="common/species_archetypes" type="{species-archotype}" />
	<file path="common/species_classes" type="{species-class}" />
	<file path="common/species_names">
		<complex entity="named_lists" type="{species-class-asclist}" />
		<complex entity="{species-class}" type="{species-class-namelist}" />
	</file>
	<file path="common/species_rights" type="{species-rights}" />

	<file path="common/star_classes">
		<complex entity="{string}" type="{star}" />
		<complex entity="random_list" type="{star-namelist}" />
	</file>
	<file path="common/starbase_buildings" type="{starbase-building}" />
	<file path="common/starbase_levels" type="{starbase-level}" />
	<file path="common/starbase_modules" type="{starbase-module}" />
	<file path="common/starbase_types" type="{starbase-type}" />
	<file path="common/strategic_resources" type="{resource}" />

	<file path="common/system_types" type="{system-type}" />


	<file path="common/terraform" type="{terraform}" entity="terraform_link" />

	<file path="common/traditions" type="{tradition}" />
	<file path="common/tradition_categories" type="{tradition-category}" />
	<file path="common/trade_conversions" type="{economic-trade}" />
	<file path="common/traits" type="{trait}" />


	<file path="events">
		<!--scope="all"-->
		<simple entity="namespace" type="{string}" min="1" />
		<complex entity="{string}" type="{event}" />
	</file>
</files>
